name: VMware Image Builder

on:
  workflow_dispatch:
  pull_request:

jobs:
  vib-validate:
    runs-on: ubuntu-latest
    env: 
      VIB_PUBLIC_URL: https://cp.bromelia.vmware.com
      CSP_API_URL: https://console.cloud.vmware.com   
      CSP_API_TOKEN: ${{ secrets.CSP_API_TOKEN }}    
    steps:
      - name: Print Information
        id: vib_info
        run: |
          echo Starting VMware Image Builder
          echo Processing SHA: ${{ github.sha }}
          echo Github Repository: ${{ github.repository }}
          echo Will download file: https://github.com/${{ github.repository }}/archive/${{ github.sha }}.zip

    

